# Generated by Django 4.0.2 on 2024-01-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_id', models.CharField(max_length=100)),
                ('Mobile', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('s_name', models.CharField(max_length=100)),
                ('c_name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('matter', models.CharField(max_length=100)),
                ('followup', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('s_name', models.CharField(max_length=100)),
                ('c_name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('matter', models.CharField(max_length=100)),
                ('followup', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
