# Generated by Django 4.0.2 on 2024-01-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_deposit_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Mobile',
            field=models.CharField(max_length=100),
        ),
    ]
