# Generated by Django 4.0.2 on 2024-01-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_staff_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Mobile',
            field=models.CharField(max_length=100),
        ),
    ]
