# Generated by Django 4.0.2 on 2024-01-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('s_name', models.CharField(max_length=100)),
                ('c_name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('matter', models.CharField(max_length=100)),
                ('followup', models.DateField(blank=True, null=True)),
                ('Purpose', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='loan',
        ),
    ]
