# Generated by Django 4.0.2 on 2024-01-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_record_delete_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deposit',
        ),
    ]
